Fix domain and csv output
apify/actor-google-search-scraper pull request #109
Opened 2022-01-14 20:42 UTC by lhotanok

Fixes #86

Test input:
```json
{
  "queries": "https://google.com/search?q=praha&sxsrf=AOaemvI0H2Cz2qAt4VSZXlwMsyg7X--zqw%3A1634903332760&source=hp&ei=JKVyYeDJKsuExc8PnfK94AM&iflsig=ALs-wAMAAAAAYXKzNPNNaP_7RVWFoN_RLi9TWonCBzs7&ved=0ahUKEwjg64zD-d3zAhVLQvEDHR15DzwQ4dUDCAc&uact=5&oq=praha&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgjECcyBAgjECcyCAgAEIAEELEDMggILhCABBCxAzIICC4QgAQQsQMyCAguEIAEELEDMggILhCABBCxAzIICC4QgAQQsQMyCAguEIAEELEDOgcIIxDqAhAnOgQIABADOgsIABCABBCxAxCDAToLCC4QgAQQxwEQrwE6BQgAEIAEOhEILhCABBCxAxCDARDHARCvAToOCC4QgAQQsQMQxwEQrwE6EQguEIAEELEDEIMBEMcBENEDUIAtWJsxYPU3aAFwAHgAgAGOAYgB3wSSAQMwLjWYAQCgAQGwAQo&sclient=gws-wiz",
  "languageCode": "en",
  "resultsPerPage": 100,
  "maxPagesPerQuery": 1,
  "saveHtml": false,
  "saveHtmlToKeyValueStore": false,
  "mobileResults": false,
  "includeUnfilteredResults": false,
  "maxConcurrency": 10,
  "countryCode": "",
  "csvFriendlyOutput": true
}
```

Output example for csv friendly option (organic + paid results only, should they be expanded with some metadata such as `searchQuery` from a detailed output?):

```json
[{
  "type": "organic",
  "title": "Prague - Wikipedia",
  "url": "https://en.wikipedia.org/wiki/Prague",
  "displayedUrl": "https://en.wikipedia.org › wiki › Prague",
  "description": "The Czech name Praha is derived from an old Slavic word, práh, which means \"ford\" or \"rapid\", referring to the city's origin at a crossing point of the Vltava ...Country: Czech RepublicHighest elevation: 399 m (1,309 ft)Founded: 5th centuryDemonym(s): Praguer‎History of Prague · ‎Old Town · ‎Timeline of Prague · ‎Prague Castle",
  "emphasizedKeywords": [
    "Praha"
  ],
  "siteLinks": [],
  "productInfo": {}
},
{
  "type": "organic",
  "title": "Prague.eu - Praha",
  "url": "https://www.prague.eu/en",
  "displayedUrl": "https://www.prague.eu › ...",
  "description": "Prague's official tourist information site. Here you will find information about Prague's sights and other places of interest, a calendar of events, ...",
  "emphasizedKeywords": [],
  "siteLinks": [],
  "productInfo": {}
}]
```

2022-01-19 15:51 UTC, petrpatek approved these changes

2022-01-19 17:20 UTC, metalwarrior665 commented
@lhotanok Thanks. 
- Yes, please merge each item with the search info and also please 
- add a `position` field (starting with 1, not 0 :D ) because now the results could get mixed up. We can add this even to the "normal" output so that we are consistent

2022-01-19 17:27 UTC, metalwarrior665 requested changes
Few comments

2022-01-19 17:27 UTC, metalwarrior665 commented on INPUT_SCHEMA.json
> +        "title": "CSV friendly output",
I would try to explain shorty what is means. E.g. `CSV friendly output (1 result on 1 row)`

2022-01-19 17:27 UTC, metalwarrior665 commented on src/extractors/mobile.js
> +                        .map((_i, e) => $(e).text().trim()).toArray(),
Please change these back to `el` which is a standard as far as I know

2022-01-19 17:27 UTC, metalwarrior665 commented on src/tools.js
> +    deduplicateKeywords(datasetResults);
I think this is not what we want. Having multiple same `emphasizedKeywords` gives the user information that this keywords repeats often in the text so it is useful to have duplicates. Or what is your reason?

2022-01-19 17:28 UTC, metalwarrior665 requested changes

2022-01-19 17:28 UTC, metalwarrior665 commented on INPUT_SCHEMA.json
> +        "description": "If checked, the crawler will return results in a structure suitable for CSV format.",
This should also explain that only organic and paid results are included

2022-01-23 17:07 UTC, lhotanok commented on src/extractors/mobile.js
> +                        .map((_i, e) => $(e).text().trim()).toArray(),
I changed it to get rid of eslint warnings:

```
'el' is already declared in the upper scope on line 66 column 70. eslint (no-shadow)
```

Should these warnings be ignored explicitly? Or some better name could be used for the inner `el`, such as `element`?

2022-01-23 17:52 UTC, lhotanok commented on src/tools.js
> +    deduplicateKeywords(datasetResults);
I see, I misunderstood the concept by using a testing query which always returned keywords that were exactly the same or with differences just in lowercase / uppercase format. So I thought we want to store unique keywords only.

While re-testing the actor and the `emphasizedKeywords`, I noticed the selectors probably changed as no keywords were saved at all. The old selectors are missing in the html snapshot so I'll pick the new ones that target `emphasizedKeywords`.

2022-01-26 11:49 UTC, metalwarrior665 commented on src/extractors/mobile.js
> +                        .map((_i, e) => $(e).text().trim()).toArray(),
Ah, right, I missed this. Let's keep it now

2022-01-26 11:51 UTC, metalwarrior665 commented on src/tools.js
> +    deduplicateKeywords(datasetResults);
I was thinking about stringification and wasn't sure about it as it would be yet another change to the API. But I guess it makes sense since this CSV friendly will be used mainly by manual users which don't care about API change of the output. 

So yes to stringification :) I would vote for `emphasizedKeywords: emphasizedKeywords.join(' |')` as there is less chance | will mess up the CSV structure.

2022-01-26 12:03 UTC, metalwarrior665 requested changes
Almost done :)
1. Let's update the stringification of `emphasizedKeywords`
2. Explain the CSV friendly input option shortly here - https://github.com/apify/actor-google-search-scraper/blob/master/README.md#how-to-get-one-search-result-per-row
3. Update CHANGELOG.md
4. One update with `position`. I think people would force us to do it anyway :) Currently, position works separately for each page, starts at 1 for each page in pagination. It would be better if it would be tracked per search term. We cannot rely on page * num because Google doesn't always give all num. So you will need to pass number of scraped organic for this search through userData here https://github.com/apify/actor-google-search-scraper/blob/master/src/main.js#L126
5. I would also do a separate `adPosition` only for ads and keep `position` only for organic. They are usually measured separately to organic ones.

2022-01-31 14:29 UTC, lhotanok commented
@metalwarrior665 I'll add the changes today 🙂

2022-02-14 20:12 UTC, metalwarrior665 commented
@lhotanok Time has come! Merging! Thanks a lot for the patience!

2022-02-14 20:12 UTC, merged