Separate personal description from the main one
apify/actor-google-search-scraper pull request #117
Opened 2022-05-02 12:20 UTC by irhel

2022-05-02 13:07 UTC, metalwarrior665 requested changes

2022-05-02 13:07 UTC, metalwarrior665 commented on src/extractors/desktop.js
> +        }
We will definitely want to split it into separate fields for name, company etc.

2022-05-03 08:43 UTC, metalwarrior665 requested changes
Do you have some test runs?

2022-05-03 08:43 UTC, metalwarrior665 commented on src/extractors/desktop.js
> +        }
Let's put it into `personalInfo` object. 

Also, check the code for `productInfo`, I'm afraid the selectors might be the same for products as for names

2022-05-03 10:31 UTC, irhel commented on src/extractors/desktop.js
> +        }
Tested it locally. I am not getting the fields by selectors but by the order in which they appear.

2022-05-03 10:49 UTC, metalwarrior665 approved these changes
Ok ,let's test a few cases

2022-05-03 10:49 UTC, merged