fix people also ask in desktop
apify/actor-google-search-scraper pull request #98
Opened 2021-07-16 04:42 UTC by pocesar

* update SDK
* optimize timeouts
* use node 14 language features

now looks like this:

```json
  "peopleAlsoAsk": [
    {
      "question": "Is Minecraft free now?",
      "answer": "Minecraft's tenth birthday is just around the corner, and to celebrate, the very first version of the game is now available to play for free, in your browser.",
      "url": "https://www.pcgamesn.com/minecraft/minecraft-classic",
      "title": "Minecraft Classic is now available to play for free in your browser ...",
      "date": "8 de mai. de 2019"
    },
    {
      "question": "Can I download Minecraft for free?",
      "answer": "Minecraft is available for download from both Apple App Store and Google Play Store. Minecraft is not a free game and one needs to purchase it before downloading it on your Android or iOS device. The game comes with some interesting features including Creative Mode that comes with unlimited resources.",
      "url": "https://www.mysmartprice.com/gear/minecraft-download-pc-mobile/",
      "title": "Minecraft Free Download: How to Download Minecraft Game Online ...",
      "date": "7 de jul. de 2021"
    },
    {
      "question": "How much is Minecraft on PC?",
      "answer": "The game is currently available for $26.95 for PC, which I'll review here. Minecraft looks great on a high-end gaming PC, but the rest of us surely appreciate how well it performs on even a standard desktop computer.",
      "url": "https://www.pcmag.com/reviews/minecraft-for-pc",
      "title": "Minecraft (for PC) Review | PCMag",
      "date": ""
    },
    {
      "question": "What is the point of Minecraft?",
      "answer": "In Minecraft, there are two main game modes: Survival and Creative. In Survival mode, the goal\\u2026is to survive. Players appear in a new world and are challenged to use its resources to build shelter, find food, and craft tools to help them construct the universe they want to live in.",
      "url": "https://www.mopop.org/about-mopop/the-mopop-blog/posts/2019/october/what-s-the-big-deal-with-minecraft/",
      "title": "What's the Big Deal With Minecraft? - MoPOP",
      "date": "30 de out. de 2019"
    }
  ]
```

2021-07-16 09:23 UTC, metalwarrior665 reviewed
Awesome. Just not sure about the smaller timeout.

2021-07-16 09:23 UTC, metalwarrior665 commented on src/main.js
> +        requestTimeoutSecs: 50,
Are you sure about this? SERPs are slow sometimes, this might get into more retries.

2021-07-16 19:25 UTC, pocesar commented on src/main.js
> +        requestTimeoutSecs: 50,
@metalwarrior665 yes, sometimes it takes 20-30 seconds, but 180 is definitely excessive. unsupported parameters make it stuck forever, like using `gl` or manually setting the provider

2022-02-17 13:32 UTC, zpelechova commented
Any idea why this is not merged @metalwarrior665 @pocesar , please?

2022-02-17 13:34 UTC, metalwarrior665 commented
@zpelechova I asked @pocesar to try to resolve the conflicts.

2022-02-18 06:56 UTC, pocesar commented
<details>
<summary>Sample</summary>

```json
{
  "#debug": {
    "requestId": "a2UqTfqlcFmzXrE",
    "url": "http://www.google.com/search?hl=pt&q=minecraft",
    "method": "GET",
    "retryCount": 0,
    "errorMessages": [],
    "statusCode": 200,
    "durationSecs": 8.45
  },
  "#error": false,
  "searchQuery": {
    "term": "minecraft",
    "device": "DESKTOP",
    "page": 1,
    "type": "SEARCH",
    "domain": "google.com",
    "countryCode": "US",
    "languageCode": "pt",
    "locationUule": null,
    "resultsPerPage": 10
  },
  "url": "http://www.google.com/search?hl=pt&q=minecraft",
  "hasNextPage": true,
  "resultsTotal": 509000000,
  "relatedQueries": [
    {
      "title": "Minecraft grátis",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Minecraft+gr%C3%A1tis&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhEEAE"
    },
    {
      "title": "Minecraft: Education",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Minecraft:+Education&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhKEAE"
    },
    {
      "title": "Minecraft Java Edition",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Minecraft+Java+Edition&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhDEAE"
    },
    {
      "title": "minecraft.net download",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=minecraft.net+download&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhIEAE"
    },
    {
      "title": "Minecraft download grátis",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Minecraft+download+gr%C3%A1tis&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhHEAE"
    },
    {
      "title": "Window minecraft",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Window+minecraft&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhFEAE"
    },
    {
      "title": "Skin minecraft",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Skin+minecraft&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhGEAE"
    },
    {
      "title": "Mojang",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Mojang&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQ1QJ6BAhCEAE"
    }
  ],
  "paidResults": [],
  "paidProducts": [],
  "organicResults": [
    {
      "title": "Minecraft | Code.org",
      "url": "https://code.org/minecraft",
      "displayedUrl": "https://code.org › minecraft",
      "description": "Minecraft Hour of Code Tutorials · Tale of Two Villages. Learn coding basics and explore diversity and inclusion with your students in Minecraft: Education ...",
      "emphasizedKeywords": [
        "Minecraft",
        "Minecraft"
      ],
      "siteLinks": [],
      "productInfo": {}
    },
    {
      "title": "Minecraft Wiki – The Ultimate Resource for Minecraft",
      "url": "https://minecraft.fandom.com/wiki/Minecraft_Wiki",
      "displayedUrl": "https://minecraft.fandom.com › wiki",
      "description": "Minecraft is a 3D sandbox game developed by Mojang Studios where players interact with a fully modifiable three-dimensional environment made of blocks and ...",
      "emphasizedKeywords": [
        "Minecraft"
      ],
      "siteLinks": [],
      "productInfo": {}
    },
    {
      "title": "Play Minecraft with PC Game Pass - Xbox",
      "url": "https://www.xbox.com/en-US/games/minecraft",
      "displayedUrl": "https://www.xbox.com › games",
      "description": "Minecraft is a game about placing blocks and going on adventures. Build anything you can imagine with unlimited resources in Creative mode, or go on grand ...",
      "emphasizedKeywords": [
        "Minecraft"
      ],
      "siteLinks": [],
      "productInfo": {}
    }
  ],
  "peopleAlsoAsk": [
    {
      "question": "Is Minecraft for free?",
      "answer": "You can play Minecraft for free on your web browser by heading to classic.minecraft.net, with no need to download or install anything.",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Is+Minecraft+for+free%3F&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQzmd6BAgYEAU",
      "title": "How to play Minecraft for free | Radio Times",
      "date": "02/12/2021"
    },
    {
      "question": "How does Minecraft cost?",
      "answer": "Versions and Pricing TL;DR Minecraft is $30 for Bedrock Edition and $26.95 for Java Edition.",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=How+does+Minecraft+cost%3F&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQzmd6BAgfEAU",
      "title": "The Price of Nostalgia: How Much Does Minecraft Cost? - Apex Hosting",
      "date": "07/09/2020"
    },
    {
      "question": "How do you download Minecraft for free?",
      "answer": "How to download Minecraft for free: This Microsoft game will get you hooked in no timeAlso read: Looking for a smartphone? ... Step 1: Open your PC and go to Microsoft Store.Step 2: Look for Minecraft for Windows 10 and click on it. ... Step 3: Click on the Free Trial option.Mais itens...•",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=How+do+you+download+Minecraft+for+free%3F&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQzmd6BAgkEAU",
      "title": "How to download Minecraft for free: This Microsoft game will get you ...",
      "date": "10/07/2021"
    },
    {
      "question": "Is Minecraft Classic Free?",
      "answer": "To mark the game's 10-year anniversary, Minecraft-developer Mojang has released Minecraft Classic as a browser game which can now be played for free.",
      "url": "https://www.google.com/search?hl=pt-PT&gl=us&q=Is+Minecraft+Classic+Free%3F&sa=X&ved=2ahUKEwjl-PnI1Yj2AhXUj4kEHd7fBGsQzmd6BAghEAU",
      "title": "Minecraft Classic Released as Free Browser Game to Celebrate 10 ...",
      "date": "09/05/2019"
    }
  ],
  "customData": null
}
```
</details>

2022-02-18 11:52 UTC, metalwarrior665 requested changes
2 important points

2022-02-18 11:52 UTC, metalwarrior665 commented on package.json
> -		"chrono-node": "^2.3.5"
You need to include the chrono-node, it is used in parsers now.

2022-02-18 11:52 UTC, metalwarrior665 commented on src/extractors/ensure_absolute_url.js
> +    ).concat(hostname)).toString();
Won't this version crash on undefined `maybeUrl` or `maybeUrl`? The old version just returned `maybeUrl`

2022-02-23 16:18 UTC, metalwarrior665 requested changes

2022-02-23 16:18 UTC, metalwarrior665 commented on src/extractors/ensure_absolute_url.js
>  };
This is a breaking change and also a bad UI. In case `maybeUrl` is `undefined` which might happen because it was using scraped links, you get `https://google.com/undefined` instead of `undefined` as before. Please make the output same as before

2022-02-23 18:41 UTC, pocesar commented on src/extractors/ensure_absolute_url.js
>  };
done

2022-02-24 09:05 UTC, metalwarrior665 approved these changes
Should be good now, thanks

2022-02-24 09:06 UTC, merged